# Generated by Django 2.2 on 2020-05-22 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_first',
            field=models.BooleanField(default=False),
        ),
    ]
